# ESTO ES UN COMENTARIO
# Todo lo que est치 a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: sebas # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "npub1rdhvn57kh2xk0n23d3kuu20r00scwvn02w8tvnns40ajthgrmqpqnkree5" # Entre comillas dobles

# Configuraci칩n Global
html:
# title: Este valor no funciona porque esta comentado
  title:  "游볨| Sebashack"

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  cover_color: "#ff7070"

# Configuraci칩n Central
main:
  title: Sebastian Lujan
#podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que est치 en blanco
  # Sacale 

  - title: instagram
    icon: instagram
    url: https://www.instagram.com/sebastianl30

  - title: "@gseba_lujan"
    icon: twitter
    url: https://twitter.com/gseba_lujan
    
# - title: LinkedIn # Este es el nombre del bot칩n
#   icon: linkedin # Este es el nombre del icono (si queres a침adir una red social nueva, prest치 atencion que es todo con min칰scula)
#   url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionar치 al hacer click

  - title: Github
    icon: github
    url: https://github.com/sebastianlujan

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guard치 el archivo haciendo click en Commit Changes, abajo
# Volv칠 a las instrucciones
